### ISSUE TITLE
The issue of the groundTruth

### ISSUE THREAD

**Issue by XinZhangRadar** [SpaceNetChallenge/SpaceNet_Off_Nadir_Solutions#2]
I have downloaded the data AOI6, but I found the groundtruth of  the different off nadir angle images are same ,that means the groundtruth of the Very Off-Nadir Images are wrong, So how can I do for the Very Off-Nadir Images' labels?

**Comment by nrweir** [comment]
There is only one set of ground truth annotations for the whole dataset, which represents the actual ground footprint of all of the buildings - see https://github.com/SpaceNetChallenge/utilities/issues/115
